[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["mupdf"]
  included_files = [
    "netlify/functions/assets/**",
    "netlify/functions/helpers/certificate-template.png",
    "netlify/functions/helpers/AlexBrush-Regular.ttf"
  ]
